apiVersion: v1
kind: Service
metadata:
  name: rtsp-load-balancer-service
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 554
    targetPort: 554
    protocol: TCP
    name: rtsp
  selector:
    app: rtsp-proxy
