apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cjlarose@gmail.com

    privateKeySecretRef:
      name: acme-client-private-key-letsencrypt-staging

    solvers:
    - selector: {}
      dns01:
        digitalocean:
          tokenSecretRef:
            name: digital-ocean-credentials
            key: personal-access-token
