---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lancache-dns
  namespace: media
  labels:
    app: lancache-dns
spec:
  selector:
    matchLabels:
      app: lancache-dns
  template:
    metadata:
      labels:
        app: lancache-dns
    spec:
      containers:
      - name: lancache-dns
        image: lancachenet/lancache-dns@sha256:2d203f1451af159e92140db0b3019cc70a49758f394a2a973a64e912174956e6
        imagePullPolicy: IfNotPresent
        ports:
        - name: dns-udp
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
        env:
        - name: USE_GENERIC_CACHE
          value: "true"
        - name: LANCACHE_IP
          value: "172.16.20.17"
