version: '3'
services:
  plex:
    image: plexinc/pms-docker
    network_mode: host
    environment:
      TZ: 'America/Los_Angeles'
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - ${PLEX_DIR}/config:/config
      - ${PLEX_DIR}/transcode:/transcode
      - ${PLEX_DIR}/media:/data
