apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: restic-secret
  namespace: default
spec:
  encryptedData:
    RESTIC_PASSWORD: AgBYL5DMCa1AKd0zFzNgok6DH6w9hxbdmw9o+iUbLUcJb8QJvHAX/FvV7+UiJc9ih7VWjPyDCxI1L0KLOZuegIr3af0s+i7AUKFR6rN0rb3/PQeNEP6Vbg3N6VIOBJugpGpvxaeSMUNkL6Gt6wLlJ+SLUYIb90zmWWxVwT/hdeYZyJDb+GU4NTZJkwONBmsdbEJOYkpiUqbzgyv8GGyGCLcdF92cAmpcuI/wBmss7Faw8rfEtzSAdqFBGS6ZXiRCyMOMDGKybbOk1t+UVC5FbBSDM/i0tdwC9Wf9irsS5D8n2xCLOEXzf9AcYLJxrU3Y2j0zmts3P8WXAWeQ4WIXDsxl2L7W35rnt4G+RnpJx+MyjvL7/z4uKYWGMiQeic1WuJ7Z4AG/iZkxYR7Vp/HvOXafXQShZGK4VmZ2RzRaxygRNYd2tSu9kD2pVj9/UP/ZzbHGVQiKq6R6cB2kihEUbyMJnE3WhVxo0PuI6e2aUtYqW9/6LrhTKB8eiHH8alAMu3avnC4DCzJxz/60pus1NP8zJ/lu/hun8+JcHs8FjFsuuCXXCWaKCkiyjjEItbZA3HAQOgkQtzRFSforDFCZMKeLnI/7h7i74fix/rGuXzk/Nr0Yq+NN7PMqRSmBXxqxSGiB5s3WX0ozBRsK1vSY3e5LW27EjB99Z2RPKGv0otfFppSnBpcWihhLtvuAFJMrsbN8ADkVQz4m6NJb/VZeiPHHBAvHoQxNJlc=
