---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
  labels:
    app: plex
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.sonarr: "semver:~1"
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostname: plex-k3os
      containers:
      - name: plex
        image: plexinc/pms-docker:1.19.5.3112-b23ab3896
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 32400
          protocol: TCP
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: system-preferences
              key: time-zone
        - name: PLEX_UID
          valueFrom:
            configMapKeyRef:
              name: users-and-groups
              key: uid.plex
        - name: PLEX_GID
          valueFrom:
            configMapKeyRef:
              name: users-and-groups
              key: gid.plex
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-credentials
              key: claim
        - name: CHANGE_CONFIG_DIR_OWNERSHIP
          value: "false"
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 32400
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: plex-config
          mountPath: "/config"
        - name: plex-transcode
          mountPath: "/transcode"
        - name: media
          mountPath: "/data"
      volumes:
      - name: plex-config
        persistentVolumeClaim:
          claimName: pvc-nfs-client-provisioner-plex-config
      - name: plex-transcode
        emptyDir:
          medium: Memory
      - name: media
        persistentVolumeClaim:
          claimName: pvc-nfs-client-provisioner-media
