apiVersion: v1
kind: Service
metadata:
  name: plex-load-balancer-service
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: k3os
spec:
  type: LoadBalancer
  ports:
  - port: 32400
    targetPort: 32400
    protocol: TCP
    name: http
  selector:
    app: plex
  loadBalancerIP: 172.16.20.17
