apiVersion: v1
kind: Service
metadata:
  name: lancache-http-load-balancer-service
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: lancache
  loadBalancerIP: 172.16.20.20
