---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bumpin-time
  namespace: media
  labels:
    app: bumpin-time
spec:
  selector:
    matchLabels:
      app: bumpin-time
  template:
    metadata:
      labels:
        app: bumpin-time
    spec:
      containers:
      - name: bumpin-time
        image: quay.io/cjlarose/bumpin-time:password
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: bumpin-time-credentials
              key: password
        - name: WOL_MAC
          value: d0:50:99:2f:e4:d4
        - name: WOL_ADDRESS
          value: 172.16.10.28
