---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-plex-transcode-hdd
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.0
spec:
  releaseName: nfs-client-provisioner-plex-transcode-hdd
  chart:
    repository: https://charts.helm.sh/stable
    name: nfs-client-provisioner
    version: 1.2.8
  forceUpgrade: true
  values:
    nfs:
      server: truenas.toothyshouse.com
      path: /mnt/storage/plex-transcode
      mountOptions:
        - "nfsvers=3"
        - "nolock"
    storageClass:
      name: "nfs-plex-transcode-hdd"
