---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-transmission-downloads
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1.0
spec:
  releaseName: nfs-client-provisioner-transmission-downloads
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.8
  forceUpgrade: true
  values:
    nfs:
      server: freenas.toothyshouse.com
      path: /mnt/storage/transmission/completed
      mountOptions:
        - "nfsvers=3"
        - "nolock"
    storageClass:
      name: "nfs-transmission-downloads"
