---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner-transmission-root
  namespace: media
spec:
  releaseName: nfs-client-provisioner-transmission-root
  chart:
    repository: https://charts.helm.sh/stable
    name: nfs-client-provisioner
    version: 1.2.8
  forceUpgrade: true
  values:
    nfs:
      server: truenas.toothyshouse.com
      path: /mnt/storage/transmission
      mountOptions:
        - "nfsvers=3"
        - "nolock"
    storageClass:
      name: "nfs-transmission-root"
