---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  namespace: media
  labels:
    app: jackett
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.jackett: "glob:amd64-v*"
spec:
  selector:
    matchLabels:
      app: jackett
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
      - name: jackett
        image: linuxserver/jackett:amd64-v0.14.302-ls48
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 9117
          protocol: TCP
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: system-preferences
              key: time-zone
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: users-and-groups
              key: uid.jackett
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: users-and-groups
              key: gid.jackett
        volumeMounts:
        - name: jackett-config
          mountPath: "/config"
        - name: jackett-downloads
          mountPath: "/downloads"
      volumes:
      - name: jackett-config
        persistentVolumeClaim:
          claimName: pvc-nfs-client-provisioner-jackett-config
      - name: jackett-downloads
        persistentVolumeClaim:
          claimName: pvc-nfs-client-provisioner-jackett-downloads
