apiVersion: v1
kind: Service
metadata:
  name: onvif-load-balancer-service
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: onvif-proxy
