kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: heimdall-network-policy
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: heimdall
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: nginx-ingress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              name: kube-system
      ports:
      - protocol: UDP
        port: 53
    - to:
      - ipBlock:
          cidr: "10.42.0.0/16"
      ports:
      - protocol: TCP
        port: 80
    - to:
      - ipBlock:
          cidr: "10.43.0.0/16"
      ports:
      - protocol: TCP
        port: 80
