apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 0.14.1
  values:
    extraArgs:
      - --dns01-recursive-nameservers="1.1.1.1:53"
      - --dns01-recursive-nameservers="1.0.0.1:53"
      - --dns01-recursive-nameservers-only
