---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: nginx-ingress-media
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.34.2
  values:
    nfs:
      server: 192.168.50.141
      path: /mnt/storage/media
      mountOptions:
        - "nolock"
    storageClass:
      name: "nfs-media"
