---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: nginx-ingress-media
  chart:
    repository: https://charts.helm.sh/stable
    name: nginx-ingress
    version: 1.34.2
  values:
    controller:
      service:
        type: "LoadBalancer"
        loadBalancerIP: 172.16.20.17
        annotations:
          metallb.universe.tf/allow-shared-ip: k3os
      extraArgs:
        default-ssl-certificate: media/toothyshouse-com-tls
