---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: media
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~1
spec:
  releaseName: nginx-ingress-media
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.34.2
  values:
    controller:
      service:
        type: "LoadBalancer"
      extraArgs:
      - --default-ssl-certificate=toothyshouse-com-tls
