---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: public-nginx-ingress
  namespace: media
spec:
  releaseName: public-nginx-ingress-media
  chart:
    repository: https://charts.helm.sh/stable
    name: nginx-ingress
    version: 1.34.2
  values:
    controller:
      service:
        type: "LoadBalancer"
        loadBalancerIP: 172.16.20.23
        annotations:
          metallb.universe.tf/allow-shared-ip: k3os
      extraArgs:
        default-ssl-certificate: media/toothyshouse-com-tls
        ingress-class: public-nginx
