apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: media
spec:
  releaseName: sealed-secrets
  chart:
    repository: https://bitnami-labs.github.io/sealed-secrets
    name: sealed-secrets
    version: 1.15.0-r1
