apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mariadb
  namespace: default
spec:
  encryptedData:
    password: AgCUhnkPRbdiiR0E1Tp1ZTRMgA9DfYRMvhJjyIV7FRqIlnwLNG4cDAW/RwlfmK7aid8oXxK/ptloafs7cUOy9dnoWAmhtMRxif9C1oLM/OHp1KlPcjBAGTThF9u2MGLUckgerHvSlgY+DtmbRzsvYdwzVGBrNybyxyFvpap29HciJPnH5KsdxMFKGmAk9+LMLw3h9pJbAMkYO4qZB91be0CBUtnFoINRqTyBqrwqD4cLoVDdKoLO/a56wPYaf1NcKvU5mZ987s2Ao8QyFAHQ8kDZJgESz0AmarlGP67MNF/fm8TGPD4SP1GxtzcOFH2tD/41h3gzoOdu2da+LeCJRgDJewgnvHVeotQvXbw26dvO8+0yycHM9gsJjKHxzco0LjvM+2OxLYB9lhmp7t+7E3qEEeN+iHpueUzMonIGEQBJiuAdcrZGrZ7555TT1m/rzjRC2DYxP5hNJPx8kAuOEydqT0L/GlT0W3M1guOlp0lsI6uLRUTtBIBzC+qHs55JlIabAtOpbOOkqMWIIud4tJ2e9E77t7GKsidXH3VDqqmX9XBLI8Lg+0P0nSsVb/4XOvI2rjqzLaO/2oN26dbyremLQg5jW/gLyvzq8HBlBQDsUQKSzIKDeWL6rCSaM8iLnG+PeiZS9ezSsu3Hj99dkGL3+/eKy2CqU1d+poF7CiDklIymDuGoVmPZqBtZ/sMnzweChPNRl/VnA1xfBqJL8umy
