apiVersion: v1
kind: Service
metadata:
  name: lancache-dns-udp-load-balancer-service
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: k3os
spec:
  type: LoadBalancer
  ports:
  - name: dns-udp
    port: 5353
    targetPort: 53
    protocol: UDP
  selector:
    app: lancache-dns
  loadBalancerIP: 172.16.20.17
