---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria
  namespace: media
  labels:
    app: terraria
spec:
  selector:
    matchLabels:
      app: terraria
  template:
    metadata:
      labels:
        app: terraria
    spec:
      containers:
      - name: terraria
        image: cjlarose/terraria-vanilla:1404
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - |-
            trap : TERM INT
            sleep infinity &
            wait
        ports:
        - name: terraria
          containerPort: 7777
          protocol: TCP
        volumeMounts:
        - name: terraria
          mountPath: /opt/terraria/serverconfig.txt
          subPath: config/serverconfig.txt
        - name: terraria
          mountPath: /worlds
          subPath: worlds
      volumes:
      - name: terraria
        persistentVolumeClaim:
          claimName: pvc-nfs-client-provisioner-terraria
