apiVersion: v1
kind: Service
metadata:
  name: terraria-load-balancer-service
  namespace: media
spec:
  type: LoadBalancer
  ports:
  - port: 7777
    targetPort: 7777
    protocol: TCP
    name: http
  selector:
    app: terraria
