kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: iperf-network-policy
  namespace: media
spec:
  podSelector:
    matchLabels:
      app: iperf
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: '172.16.10.0/24' # pre-SNAT address
  egress:
  - to:
    - ipBlock:
        cidr: '172.16.10.0/24' # post-DNAT address
