kind: Pod
apiVersion: v1
metadata:
  name: test-pvc-pod
  namespace: demo
spec:
  containers:
  - name: test-pvc-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - >
        addgroup -g 1000 plex &&
        adduser -D -G plex -u 1000 plex &&
        su -c 'touch /mnt/SUCCESS && exit 0 || exit 1' - plex
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: pvc-nfs-client-provisioner-media
