kind: Pod
apiVersion: v1
metadata:
  name: test-pvc-pod
  namespace: demo
spec:
  containers:
  - name: test-pvc-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "tail -f /dev/null"
    volumeMounts:
      - name: nfs-pvc
        mountPath: "/mnt"
  restartPolicy: "Never"
  volumes:
    - name: nfs-pvc
      persistentVolumeClaim:
        claimName: pvc-nfs-client-provisioner-media
