apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: toothyshouse-com-certificate
  namespace: media
spec:
  secretName: toothyshouse-com-tls
  issuerRef:
    name: letsencrypt-staging
  dnsNames:
  - '*.toothyshouse.com'
  - toothyshouse.com
