apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-credentials
  namespace: media
spec:
  encryptedData:
    webpassword: AgAdJ/EDwDWch9+H9vnICCpLBBsUXSK28J7ePzlF86h4vuP/6H7Sa08aUPH6/Fg9em22iz+3OL28KAhE5v/SjerYwcqV8PEPSLWIHoapKJ8B3Wfulbk2t/ra2Aag3leaRujJgo+ZFUE90rcxBsdJJhBu0RSJRDDav/zEL7Bq3WjPj/6XM1N/Rd+W5aGLJ3x1KyX6PGL/OQQ90fuIPf6ssp4mSi55ra1BEAxpNKwDmU2mYzC5N13bmReosJOXC+tkwyvtAc90lDV3y2fS/LoxLUgJ1LRI+sHQNjy2DyKIpMZ9Huf2AzMjR/YwaJWUV5Peosba0SJFwU6xDN2n5TIA2S1Jd4G8xRVcnEEb8RbwpXIV7FBtXBAs1/ZnfCl1q5WtQSKlRBrP6KzUj8wEXNsPjExhbCdpAHn4SZSVGyPgHw54cP3Jhx44CIGNjlYIMQnl8TPYSYfrrHTgg5PI4iVdKVzMX0mzdX9egzwZ4b0QvuLkPd7FVwjKHHmHjMpjNMaDdpF2e+qOXnJBogdE5/xj26n5JR7Le5csIMKDc0B9NVX/QjjIJShCDb6xtzJzu0x0t4355+zYQuoKrvRw6NrVoMS1Rp+qbEbpDNyXRw8u6QZn5jXXVEHto2a/ZuXMCs40gOg/uQjrvcIG5hyJcL1drrvQu0BNzevG8Sryb3aF19T74jo6Ve3nrSvGtAT5if7oLFrGwUR09mt1Hbufa6wPv5fSz74upAxL1mg=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-credentials
      namespace: media

