apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: plex-credentials
  namespace: media
spec:
  encryptedData:
    claim: AgBSZkyJiHcejgE4/ToAdWmy+xtstkCR7kZbJobAAMdYuuRzBn/2oklPjRr9EdvDhkvefamBtkPWYAQO3ZDrpnjIRs7ewilVyovC4UZwIlt3B+GSwCBlgEsbnVy3gzsagmfnxI03SPsL9Mo90U8jTgbm8/1U7aBZUsgt46YgaD4SnLPN4qXkaUsLOUR+t9MsvDBGQS3A9fZSEg1zymQWlI57XUAkzM016mkPA8hv/XDaDuqYAQxKVDGec3twGfB2u65VjnFVbRh7RqJmGuGFSGEmniaKgB/nWrS2GA/5oqNO1yeF27R4APmQwHhn6ScP5Sz9WcUy+gRT5/kOWwX/9WHXymAsiVTZteJgv/JPnXltFZBadh3+ZZkoZKJPZQV46jQhHxvQ59vE14dIzNM3s5JmxuF2f91pZwDMN/EMkNebnxDMKV+IcNYX0cORs6rGVU9KCi/NpWS1kvtFAvlFnJ7t+qizPKpSAMW7VE8w55co0M3aaI5zMIwpl2zFPywO3g4r7EoMfjiYfLjQohT6wrVBxnhSY+ELSOlF8E/JXS3mnUtgAtEyyFaNV/OEqCDqgqPptPNX5h64F+6iyZPE5HU7xzwWgjwRUYsYOdQPogDHnzr84rVzAsOpN0oNSGSNYukJawB9fOr9jVwt1lpw3Kl1S4nSCuA8xcT0Vrn3Bap0qdd6Zc/zyHLs8nyS++SndBByO5S93NgrXXLXfU15PS0TmQy9L2VvHIPTzg==
  template:
    metadata:
      creationTimestamp: null
      name: plex-credentials
      namespace: media
